
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-15
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-15
pull_requests: [{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-epic1-frontend3","number":41,"title":"Added Menu Items placeholder page","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-15/pull/41"},{"author":{"id":"U_kgDOB70X2g","is_bot":false,"login":"haohuant","name":""},"headRefName":"Calvin-epic1-frontend1","number":40,"title":"Added Table for Meals, incl. fixtures, tests, and stories","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-15/pull/40"},{"author":{"id":"MDQ6VXNlcjY3MjQ3MzM0","is_bot":false,"login":"riasinha","name":""},"headRefName":"DatabaseTable","number":39,"title":"Updated Database table for DiningCommonsReview","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-15/pull/39"}]
