
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-15
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-15
pull_requests: [{"author":{"id":"U_kgDOBnFNow","is_bot":false,"login":"sophiaray2101","name":""},"headRefName":"sophiaray2101-menuItemReview-get-id","number":54,"title":"MenuItemReview GET (by logged in user) endpoint","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-15/pull/54"},{"author":{"id":"MDQ6VXNlcjU0NDg5MTI4","is_bot":false,"login":"HiDropsy","name":""},"headRefName":"hidropsy-14-1","number":53,"title":"Add endpoints for menu item","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-15/pull/53"},{"author":{"id":"U_kgDOBnFNow","is_bot":false,"login":"sophiaray2101","name":""},"headRefName":"sophiaray2101-controller-post","number":50,"title":"MenuItemReview post (all users)","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-15/pull/50"}]
